### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by zhunnan** [bywang2018/security-dataset#2]
how to interface image with your provided model?

**Comment by bywang2018** [comment]
Do you mean you want to use a pre-trained model to visualize the test results? You can visualize the detection result with the following command:
> from mmdet.apis import init_detector, inference_detector
> import mmcv
> config_file = 'configs_path'
> checkpoint_file = 'ckpt_path' 
> model = init_detector(config_file, checkpoint_file, device='cuda:0')
> img = 'img_path'
> result = inference_detector(model, img)
> model.show_result(img, result, out_file='result.jpg')

**Comment by zhunnan** [comment]
Thanks
