### ISSUE TITLE
hi, is there a pretrained model to inference

### ISSUE THREAD

**Issue by lolikonloli** [bywang2018/security-dataset#7]
Excellent Job
is there a pretrained model to inference.
rtx3080 is too new to train the model,because of CUDA,so i want to use a pretrained model to inference with my personal computer,but i dont't know whether the model i download at begining is a pretrained model.

**Comment by bywang2018** [comment]
Thanks for your appreciate！ The URL of the pretrained model is: https://drive.google.com/file/d/1ZeXInJdl-GDTAFO-aSUOgWUgsirUuame/view?usp=sharing

**Comment by lolikonloli** [comment]
> 感谢您的赞赏！预训练模型的 URL 是：https://drive.google.com/file/d/1ZeXInJdl-GDTAFO-aSUOgWUgsirUuame/view?usp=sharing

thank you vary much !!!
have a good day
